
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:30 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
